
service: gabechino

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev

functions:
  index:
    handler: handler.index
    events:
      - http:
          path: api/index
          method: get
  staticfiles:
    handler: staticfiles.staticfile
    events:
      - http:
          path: site/{url+}
          method: get
  binary:
    handler: staticfiles.binary
    events:
      - http:
          path: site/img/{pathvar+}
          method: get
  
plugins:
  - serverless-offline
  - serverless-aws-static-file-handler/plugins/BinaryMediaTypes

custom:
  apiGateway:
    binaryMediaTypes:
      - "image/png"
      - "image/jpeg"
      